import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    files: [
      "scripts/main.js",
      "scripts/core/**/*.js",
      "scripts/ui/**/*.js",
      "scripts/planner2d/**/*.js",
      "scripts/planner3d/**/*.js",
      "scripts/export/**/*.js",
      "scripts/cloud/**/*.js",
      "scripts/devtools/**/*.mjs",
    ],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        activeProfile: "readonly",
        autoSquareCurrentRoom: "readonly",
        canvas: "writable",
        clearTimeout: "readonly",
        clearFurnitureSelection: "readonly",
        console: "readonly",
        copySelectedFurniture: "readonly",
        curRoom: "writable",
        deleteSelectedFurniture: "readonly",
        dg: "readonly",
        document: "readonly",
        doRedo: "readonly",
        doUndo: "readonly",
        draw: "readonly",
        ds: "readonly",
        exportPDF: "readonly",
        exportSVG: "readonly",
        furnitureClipboard: "readonly",
        hideP: "readonly",
        isEditableTarget: "readonly",
        localStorage: "readonly",
        location: "readonly",
        multiSelFurnitureIds: "writable",
        navigator: "readonly",
        normalizeRoom: "readonly",
        panelHidden: "writable",
        pasteFurniture: "readonly",
        performance: "readonly",
        projects: "writable",
        redoSt: "writable",
        renderHome: "readonly",
        ROOM_HISTORY_PREFIX: "readonly",
        saveAll: "readonly",
        savePrj: "readonly",
        scheduleRebuild3D: "readonly",
        selectedFurnitureIndices: "readonly",
        sel: "writable",
        setTool: "readonly",
        setTimeout: "readonly",
        showP: "readonly",
        tW: "readonly",
        toggle3D: "readonly",
        toast: "readonly",
        tool: "writable",
        undoSt: "writable",
        uid: "readonly",
        updateRoomPreviewThumb: "readonly",
        updateUndoStrip: "readonly",
        vOff: "writable",
        vScale: "writable",
        window: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
  {
    files: ["scripts/devtools/**/*.mjs"],
    languageOptions: {
      globals: {
        process: "readonly",
      },
    },
  },
];
